# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SimpleApp
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'

  

  target 'SimpleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SimpleApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SimpleApp-tvOS

  target 'SimpleApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
